### ISSUE TITLE
百度旧版API已经下线

### ISSUE THREAD

**Issue by hyacz** [diegozeng/Alfred-workflow-baidu-translate#1]
<img width="594" alt="2016-04-12 11 12 04" src="https://cloud.githubusercontent.com/assets/9551197/14448879/70c614f0-009f-11e6-8fb2-588b67b9b29c.png">
现在这个workflow已经无法使用，希望能替换成新的API。

**Comment by diegozeng** [comment]
已更新"baidu translate.alfredworkflow"， 切换到新版的baidu translate API, 本地测试可以通过.
